---
apiVersion: v1 
kind: Pod
metadata: 
  name: dov-pod
  namespace: myns
  labels: 
    app: dov
spec:
  containers:
  - name: dov-container 
    image: chukmunnlee/dov-bear@sha256:483038792aba29562a4d2044e790d7d3e7e6e6f684ce1fcafc3864949c000224
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: dov-cm
    - secretRef:
        name: dov-secret
    #env:
    #- name: INSTANCE_NAME
    #  value: "my dov bear"
    #- name: INSTANCE_HASH
    #  valueFrom: 
    #    fieldRef:
    #      fieldPath: status.podIP
    ports:
    - containerPort: 3000