---
apiVersion: v1
kind: Namespace
metadata:
  name: auth

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  namespace: auth
  labels:
    app: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deploy
  template:
    metadata:
      labels:
        app: auth-deploy
    spec:
      containers:
      - name: jwt-auth
        image: chukmunnlee/jwt-auth:v1.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 3
          failureThreshold: 3
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-deploy
  name: auth-svc
  namespace: auth
spec:
  type: ClusterIP
  selector:
    app: auth-deploy
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
